### ISSUE TITLE
Add Back Button in <fiv-search-bar> component

### ISSUE THREAD

**Issue by caturandi-labs** [fivethree-team/ionic-4-components#121]
Thanks For Great and Beautiful Ionic 4 Components.

Hello author, can i add back button in search bar component ?

thanks

**Comment by garygrossgarten** [comment]
Hi @caturandi-labs ,

thank you for opening an issue. 

You can add a button in the searchbar by using either **start** or **end**, see this example:

```html
<fiv-searchbar title="Searchbar" placeholder="Search ...." (fivInputChange)="onSearchInputChanged($event)"
  (fivClose)="searchbarClosed()">
  <ion-back-button start defaultHref="home"></ion-back-button>
</fiv-searchbar>
```

If this doesn't resolve your problem you can always submit a PR or reopen the issue so we can find a different approach.

Sorry for the poor documentation, we're working on it! ;)

Cheers,

Gary
