### ISSUE TITLE
problem when opening a gallery with fiv-gallery created dynamicly by *ngFor

### ISSUE THREAD

**Issue by deissh** [fivethree-team/ionic-4-components#142]
when one of the pictures is opened, the correct one is shown first, but after a couple of seconds it changes to the first one

[Video](https://www.youtube.com/watch?v=3Bib54G0t5c)

```ts
  private info: IPostFull;
  public episode: string[];
  private spiner: any;

  public stats: {
    readed: string[],
    inprogress: string[]
    last: string
  };
```

Page template
```html
<ion-content fullpage>

  <fiv-gallery>
    <fiv-gallery-toolbar [position]="'top'">
      <fiv-gallery-toolbar-content></fiv-gallery-toolbar-content>
    </fiv-gallery-toolbar>
    <ion-grid fixed no-padding>
      <ion-row class="large">
        <ion-col size="4" *ngFor="let img of episode">
          <fiv-gallery-image [src]="img"></fiv-gallery-image>
        </ion-col>
      </ion-row>
    </ion-grid>

    <fiv-gallery-toolbar [position]="'bottom'">
      <ion-toolbar color="transparent">
        <ion-text>
          {{ info?.name }}<br>
          Глава: {{ stats?.last }}
        </ion-text>

      </ion-toolbar>
    </fiv-gallery-toolbar>

  </fiv-gallery>

</ion-content>

```

**Comment by garygrossgarten** [comment]
Hey @deissh 
I updated the Image Gallery Demo Page with some galleries using *ngFor. I don't seem to have the problem you show in the video but I would like to find out what's causing the bug on your side. Could you please share a minimal repro of the bug?

Cheers 

Gary

**Comment by deissh** [comment]
@garygrossgarten 
html:
https://github.com/deissh/anibe.app/blob/84ec7f8e442a386e159a2f42314cdef00e722287/src/app/pages/reader/reader.page.html

ts:
https://github.com/deissh/anibe.app/blob/84ec7f8e442a386e159a2f42314cdef00e722287/src/app/pages/reader/reader.page.ts

**Comment by garygrossgarten** [comment]
Please provide a small repository with a reproduction of the bug. I forked your project but I don't seem to be able to work with it.

**Comment by deissh** [comment]
ok, there will be time on weekends and I will make a repository

**Comment by deissh** [comment]
I found that the problem occurs only when the list with pictures is created after the template is drawn, that is, after the page has loaded, it receives carinks via the http request and only then they are written to a variable, for example imgs

**Comment by garygrossgarten** [comment]
I'll see what i can do about it ;)

**Comment by deissh** [comment]
you can just add `.update` commant to reload all component and his childrens.
