### ISSUE TITLE
Feature Discovery 

### ISSUE THREAD

**Issue by vasquezdennisalon** [fivethree-team/ionic-4-components#154]
I was doing a demo with feature discovery and I was throwing the following error

``` Error: No component factory found for FivFeatureDiscovery. Did you add it to @NgModule.entryComponents? ```

and literally copy the following code from your project

[Github Feature Discovery](https://github.com/fivethree-team/ionic-4-components/tree/master/src/app/pages/feature-discovery)

**Comment by marcjulian** [comment]
Thank you for your issue and sorry for the late reply.

Please import `FivFeatureDiscoveryModule` as an import to the `AppModule` this will register `FivFeatureDiscovery` as an entry component.

```typescript
import { NgModule } from '@angular/core';
import { FivFeatureDiscoveryModule } from '@fivethree/core';

@NgModule({
  imports: [
    ...
    FivFeatureDiscoveryModule,
    ...
  ]
})
export class AppModule {}
```

Also you need to import it into your page or component module where you like to use the feature discovery.
