### ISSUE TITLE
bug: bottom sheet rounded not worked

### ISSUE THREAD

**Issue by iamravisankar** [fivethree-team/ionic-4-components#158]
# Bug Report

**Fivethree version:**
[x] **0.9.x**

**Current behavior:**
Bottom sheet content border to be curved

**Expected behavior:**

Border-radius not worked
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Comment by garygrossgarten** [comment]
Hey @iamravisankar,

Thank you for opening an issue.
Can you provide a repo for reproduction?

**Comment by iamravisankar** [comment]
I just clone this and run on my machine, also run on my android device bottom sheet round not worked.

**Comment by garygrossgarten** [comment]
Hi @iamravisankar 

My bad, i removed some padding on the bottom-sheet-content that was necessary to be able to see the border-radius. Version 0.9.6 should fix your problem.

You can customize the border-radius by setting

```css
fiv-bottom-sheet-content {
  --fiv-border-radius: 12px;
  --fiv-padding: 20px;
}
```


in your css (The values above are the default values). And don't forget to add rounded="true" to your fiv-bottom-sheet-content.

Please report back if you have further problems.

Cheers

Gary

**Comment by iamravisankar** [comment]
hi @garygrossgarten  ,
   Even after again downloading the repo. and update to 0.9.6, no changes occurred can you share the screenshot please if works.
