### ISSUE TITLE
Using angular features inside Feature Discovery template

### ISSUE THREAD

**Issue by gartorware** [fivethree-team/ionic-4-components#159]
Hi there,

is there a way for using ngx-translate with Feature Discovery? Neither translate directive nor translate pipe seems to be working inside the template (angular related I guess, since the Feature Discovery Module is not loading the Translate module (obviously)). 

Data binding is not working either since createEmbeddedView is getting called with null as parameter, so no context available. I cannot figure out how to create i18n feature tours...

Thank you.

**Comment by garygrossgarten** [comment]
Hi @gartorware,

Can you provide a repo for reproduction? This sounds definitely like something that we should sort out.
In the meantime, if you find a fix, feel free to send a PR.

Cheers

Gary

**Comment by gartorware** [comment]
The problem seems more complex than I though.
I though the issue was with the ngx-translate module since neither its directive nor its pipe was working, but in fact almost no angular feature is working inside the feature template.

I mean, you can no use interpolation, directives, pipes, data binding, ...

This is a minimal repo, just ionic blank project with fivethree module installed:
https://github.com/gartorware/feature-discovery-test

This is stackblitz version:
https://stackblitz.com/edit/ionic-v4-feature-discovery

Related code is in `src/app/home`.

As you can see `ng-template #featureContent` is rendered correctly when used with `*ngIf="nullValue else featureContent"`. You can use pipes ( | uppercase), interpolation, data binding, etc.
When the same template is used for feature discovery none of these are working.

Maybe am I missing something?

**Comment by garygrossgarten** [comment]
@gartorware 

Version 0.9.6 should fix the context problem. Please try it out and report back here if you need further help.

Cheers

Gary

**Comment by gartorware** [comment]
wow such a fast fix!

Yep, I can confirm. This is fixed in 0.9.6.
I have tried it in both my own project and the stackblitz demo above. Context is fully available now. ngx-translate pipe and directive is fully working as well. Great job!

Thank you very much!!!
