### ISSUE TITLE
fiv-loading-content auto dismiss after firing

### ISSUE THREAD

**Issue by hamzahalvanaa** [fivethree-team/ionic-4-components#160]
Hello,
Congratulations to all involved for the excellent work!

I'm finding some problems with the component 'fiv-loading-content', I have successfully applied it and firing when i swiping down the screen, but it didn't dismiss automatically. I have tried to adding viewChild but nothing happens.

Maybe someone could help me, any advice appreciated. Thank you.

**Comment by garygrossgarten** [comment]
Hey @hamzahalvanaa ,
the component is not meant to dismiss automatically. You need to call `completeRefresh` on the viewchild once your loading action is done to finish.

Here is an [example](https://github.com/fivethree-team/ionic-4-components/tree/master/src/app/pages/refresh).

Please provide a code snippet or example repo if you need further help.

Cheers

Gary

**Comment by hamzahalvanaa** [comment]
How to call completeRefresh on the viewChild? I have done like this:
` @ViewChild('fivLoading', { static: false }) fivLoading: FivLoadingContent;
`

And the view like this:
```
<fiv-loading-content spinColor="dark" #content fullscreen (ionScroll)="content.completeRefresh()">
  // here goes the content
</fiv-loading-content>

```

I call completeRefresh on scroll, how to set timeout when loading is done?
