### ISSUE TITLE
bug: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by dotnetdreamer** [fivethree-team/ionic-4-components#165]
# Bug Report

**Fivethree version:**
[x] **1.0.0-alpha.11**

**Current behavior:**

I have followed the documentaion and added a simple feature discovery but its not working

**Expected behavior:**
The feature discovery should appear from component

**Related code:**
```
    <ion-tab-button class="logo-animator-container" (click)="onTabClicked('search')" #feature="fivFeature" [fivFeature]="fabContent">
      <div #logoAnimContainer></div>
    </ion-tab-button>
```
and in component:
```
  @ViewChild('feature', { static: false }) feature: FivFeature;

  ngAfterViewInit() {
      //display walkthrough
      setTimeout(() => {
        console.log(this.feature)
        this.feature.show();
      }, 3000)
  }
```
Error:
```
core.js:7376 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at FivFeatureDiscovery.setBounds (fivethree-core.js:4590)
    at FivFeature.show (fivethree-core.js:4880)
    at home.page.ts:39
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26760)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:3070)
```

**Comment by garygrossgarten** [comment]
Hey there @dotnetdreamer,

can you provide a repo for reproduction? Where do you define your "fabContent"?

**Comment by dotnetdreamer** [comment]
@garygrossgarten hi,
Unfortunately its production app, fabContent is in the home.page.html which is ionic tabs template

**Comment by garygrossgarten** [comment]
Could you try out  1.0.0-alpha.12? I just released a possible fix for this. Please report back here.

**Comment by dotnetdreamer** [comment]
i will do now ;)

**Comment by dotnetdreamer** [comment]
it works now. However, I see that its aligned abit off. See my orignal screenshot and with the discovery below:
![localhost_8101_home_tabs_dashboard(Pixel 2 XL)](https://user-images.githubusercontent.com/10280821/69815729-5f8bde00-1210-11ea-9579-5bb92e67f148.png)
![localhost_8101_home_tabs_dashboard(Pixel 2 XL) (1)](https://user-images.githubusercontent.com/10280821/69815741-674b8280-1210-11ea-8bec-c4026831b0e3.png)

**Comment by dotnetdreamer** [comment]
sorry. its working. I added abit of delay. Thanks :)

**Comment by garygrossgarten** [comment]
perfect, thank you. If you see something that you can improve feel free to submit a PR.
