### ISSUE TITLE
Stepper Mode Horizontal No Longer Working

### ISSUE THREAD

**Issue by wcooperscott** [fivethree-team/ionic-4-components#177]
After updating from 0.8.9 to 1.0.0-alpha.24 (huge jump I know), The horizontal mode has stopped working. To confirm this I downgraded back to 0.8.9 to see it working again (with many errors since it's out of date with my environment: Angular 9, Ionic 5).

Please reach out to me when you look into this and if/when it's resolved.

Thanks!

**Comment by marcjulian** [comment]
@wcooperscott can you provide a repository to reproduce your error?

**Comment by wcooperscott** [comment]
@marcjulian Here is a sample repository I just created in Ionic 5.

https://github.com/wcooperscott/FivThree-Stepper-Issue

Although `mode="horizontal"`, it still sits vertical.

Project Imports:
```
@fivethree/core          //repository readme.md states this must be imported
@angular/animations //imported to app.modules.ts
@fivethree/layout       //imported to pages/stepper/stepper.module.ts
```


```
Ionic Info:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   NodeJS : v12.16.2 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

Tested using terminal command: `ionic serve`

**Comment by wcooperscott** [comment]
This is still an issue for me. Currently withholding a production build & upload because of this.

**Comment by wcooperscott** [comment]
I've found an issue submitted. Looks like it an issue with Angular 9. Whether someone working on this repo would like to implement a working work-around or not, that is your decision.

https://github.com/ionic-team/ionic/issues/20356

Using the open-source code, I wrote my own similar version of the horizontal slider in my app.

**Comment by marcjulian** [comment]
@wcooperscott thanks for creating a repository to reproduce. I send you a PR and notived that you use an old package @fivethree/layout. All components are bundled in @fivethree/core!

I also noticed your project uses Angular 8 instead of 9. Please update angular to 9 to see if it still works.

**Comment by marcjulian** [comment]
Feel free to reach out here if you have any further questions
