### ISSUE TITLE
Can't bind to 'titleMode' since it isn't a known property of 'fiv-app-bar' ionic 5

### ISSUE THREAD

**Issue by CodingApp** [fivethree-team/ionic-4-components#179]
I'm using this package inside of ionic 5. Please guide if i'm doing something wrong. Thanks

import {
  FivAppBarModule,
  FivCenterModule,
  FivFabModule,
  FivIconModule,
  FivEditableLabelModule,
  FivFeatureDiscoveryModule,
  FivIfModule
} from '@fivethree/core';

@NgModule({
  imports: [
    IonicModule,
    CommonModule,
    FormsModule,
    TabsPageRoutingModule,
    FivAppBarModule,
    FivCenterModule,
    FivIfModule,
    FivFabModule,
    FivEditableLabelModule,
    FivIconModule,
    FivFeatureDiscoveryModule
  ],
  declarations: [TabsPage]
})

<ion-tabs #tabs>
  <fiv-app-bar slot="bottom" [titleMode]="titleMode" #bar>
    <fiv-fab [fivAppBarFab]="position" #fab>
      <fiv-icon name="home"></fiv-icon>
    </fiv-fab>

    <fiv-app-bar-tab left tab="tab1" href="/tab1">
      <fiv-icon name="search-outline"></fiv-icon>
      <ion-label>Home</ion-label>
    </fiv-app-bar-tab>
    <fiv-app-bar-tab left tab="tab2" href="/tab2">
      <fiv-icon  name="notifications-outline"></fiv-icon>
      <ion-label>Images</ion-label>
    </fiv-app-bar-tab>
    <fiv-app-bar-tab right tab="tab3" href="/tab3">
      <fiv-icon name="cart-outline"></fiv-icon>
      <ion-label>Pizza</ion-label>
    </fiv-app-bar-tab>
    <fiv-app-bar-tab right tab="tab4" href="/tab4">
      <fiv-icon name="person-outline"></fiv-icon>
      <ion-label>More</ion-label>
    </fiv-app-bar-tab>
  </fiv-app-bar>
</ion-tabs>

**Error: Can't bind to 'titleMode' since it isn't a known property of 'fiv-app-bar'.**

**Comment by marcjulian** [comment]
Which version of `@fivethree/core` are you using?

Here is an example using `@fivethree/core 1.0.0-alpha.24`
```html
<ion-tabs #tabs>
 <fiv-app-bar slot="bottom" [titleMode]="'show'" #bar>
      <fiv-fab [fivAppBarFab]="'center'" #fab>
        <fiv-icon name="color-wand"></fiv-icon>
      </fiv-fab>

      <fiv-app-bar-tab left tab="tab1" href="/tab1">
        <fiv-icon name="home"></fiv-icon>
        <ion-label>Home</ion-label>
      </fiv-app-bar-tab>
      <fiv-app-bar-tab left tab="tab2" href="/tab2">
        <fiv-icon smallIcon="add" name="pizza"></fiv-icon>
        <ion-label>Images</ion-label>
      </fiv-app-bar-tab>
      <fiv-app-bar-tab right tab="tab3" href="/tab3">
        <fiv-icon badge="1" name="basket"></fiv-icon>
        <ion-label>Pizza</ion-label>
      </fiv-app-bar-tab>
      <fiv-app-bar-tab right tab="tab4" href="/tab4">
        <fiv-icon dot="false" name="bug"></fiv-icon>
        <ion-label>More</ion-label>
      </fiv-app-bar-tab>
    </fiv-app-bar>
</ion-tabs>
```

If you can provide a reproduction repo that would be very helpful.

**Comment by CodingApp** [comment]
Thanks you so much for your reply @marcjulian 

I'm using ionic 5 and angular 9, and the version is "@fivethree/core": "^1.0.0-alpha.2"

**Comment by CodingApp** [comment]
@marcjulian i have updated it manually and seems like its fixed now. Thank you for your time!

I'm using ionic 5 and angular 9, and the version is "@fivethree/core": "^1.0.0-alpha.2"

**Solution: run npm install --save @fivethree/core@latest**
