### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by valdeca** [fivethree-team/ionic-4-components#181]
# Bug Report

**Fivethree version:**
[x] **0.9.x**

**Current behavior:**
New Ionic 5 project with tabs boilerplate. Replace the pre-created tabs with the FivAppBarModule tabs. The page is loaded with the tabs bar but not content. Also the fiv-icons trigger erros in the console.
<img width="897" alt="Screen Shot 2020-06-10 at 5 46 58 PM" src="https://user-images.githubusercontent.com/8465928/84322082-64780580-ab42-11ea-8710-97b33b8b01ba.png">
 
<img width="359" alt="Screen Shot 2020-06-10 at 5 46 19 PM" src="https://user-images.githubusercontent.com/8465928/84322035-50340880-ab42-11ea-90a6-2df8af73f5a2.png">

**Expected behavior:**
It should look like the example.

**Steps to reproduce:**
Create new Ionic 5 project, tabs template and follow the tutorial

**Comment by marcjulian** [comment]
Can you try the latest version 1.0.0-alpha.24? You will need to import the following modules for the app bar to work on your page.

```bash
FivAppBarModule,
FivFabModule,
FivIconModule,
```

**Comment by valdeca** [comment]
After importing those modules I am getting the following error:
<img width="947" alt="Screen Shot 2020-06-14 at 9 49 20 PM" src="https://user-images.githubusercontent.com/8465928/84610559-f48eb580-ae88-11ea-8b52-fc263a6a1fe7.png">

**Comment by marcjulian** [comment]
Please have a look at the installation and configration instructions: https://github.com/fivethree-team/ionic-4-components#install-the-ui-library

You need to install `@angular/animations` and import `BrowserAnimationsModule` in your `app.module.ts`

**Comment by valdeca** [comment]
Thanks Made it work I added BrowserAnimationsModule on the providers instead of import, thanks!
